# Generated by Django 5.1.4 on 2026-05-23 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(default='individual', max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('workspace_name', models.CharField(blank=True, max_length=255, null=True)),
                ('use_case', models.CharField(blank=True, max_length=255, null=True)),
                ('collaboration_goals', models.TextField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
