# Generated by Django 5.1.4 on 2026-05-23 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('meeting_id', models.UUIDField(blank=True, null=True)),
                ('webinar_id', models.UUIDField(blank=True, null=True)),
                ('meeting_title', models.CharField(max_length=255)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('action_items', models.JSONField(default=list)),
                ('key_decisions', models.JSONField(default=list)),
                ('follow_up_tasks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('meeting_id', models.UUIDField(blank=True, null=True)),
                ('recording_url', models.URLField()),
                ('transcript', models.TextField(blank=True, null=True)),
                ('speakers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transcription_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
