# Generated by Django 5.1.4 on 2026-05-23 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_id', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('meeting_type', models.CharField(choices=[('meeting', 'Meeting'), ('webinar', 'Webinar'), ('coaching', 'Coaching'), ('classroom', 'Classroom'), ('standup', 'Standup'), ('interview', 'Interview'), ('workshop', 'Workshop')], default='meeting', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('livekit_room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('participant', 'Participant'), ('observer', 'Observer')], default='participant', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_participants',
            },
        ),
    ]
