# Generated by Django 5.1.4 on 2026-05-23 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_id', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('livekit_room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webinars',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WebinarChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='webinars.webinar')),
            ],
            options={
                'db_table': 'webinar_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('options', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='webinars.webinar')),
            ],
            options={
                'db_table': 'webinar_polls',
            },
        ),
        migrations.CreateModel(
            name='WebinarQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('question', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='webinars.webinar')),
            ],
            options={
                'db_table': 'webinar_questions',
                'ordering': ['-upvotes', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPollResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('selected_option', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='webinars.webinarpoll')),
            ],
            options={
                'db_table': 'webinar_poll_responses',
                'unique_together': {('poll', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='webinars.webinar')),
            ],
            options={
                'db_table': 'webinar_registrations',
                'unique_together': {('webinar', 'user_id')},
            },
        ),
    ]
